from pathlib import Path


def read_properties(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        result[key.strip()] = val.strip()
    return result


def write_properties(path: Path, data: dict[str, str]) -> None:
    # сохраняем известный порядок + остальные ключи
    preferred = [
        "motd",
        "server-port",
        "gamemode",
        "difficulty",
        "max-players",
        "online-mode",
        "pvp",
        "spawn-monsters",
        "spawn-animals",
        "allow-nether",
        "enable-command-block",
        "view-distance",
        "simulation-distance",
        "white-list",
        "enforce-whitelist",
        "level-name",
        "level-seed",
        "level-type",
    ]
    lines = [
        "# Generated by Calista Minecraft Service",
        "#",
    ]
    seen = set()
    for key in preferred:
        if key in data:
            lines.append(f"{key}={data[key]}")
            seen.add(key)
    for key in sorted(data.keys()):
        if key not in seen:
            lines.append(f"{key}={data[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# для UI: какие поля как рисовать
FIELD_SCHEMA = [
    {"key": "motd", "label": "MOTD", "type": "text"},
    {"key": "server-port", "label": "Порт", "type": "number"},
    {"key": "max-players", "label": "Макс. игроков", "type": "number"},
    {
        "key": "gamemode",
        "label": "Режим",
        "type": "select",
        "options": ["survival", "creative", "adventure", "spectator"],
    },
    {
        "key": "difficulty",
        "label": "Сложность",
        "type": "select",
        "options": ["peaceful", "easy", "normal", "hard"],
    },
    {"key": "online-mode", "label": "Online mode", "type": "bool"},
    {"key": "pvp", "label": "PvP", "type": "bool"},
    {"key": "spawn-monsters", "label": "Мобы", "type": "bool"},
    {"key": "allow-nether", "label": "Ад", "type": "bool"},
    {"key": "enable-command-block", "label": "Command blocks", "type": "bool"},
    {"key": "view-distance", "label": "View distance", "type": "number"},
    {"key": "white-list", "label": "Whitelist", "type": "bool"},
]
