name: CD

on:
  workflow_dispatch:

jobs:
  test-connection:

    runs-on: ubuntu-latest

    steps:

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.CALISTA_HOST }}
          username: calista-deploy
          key: ${{ secrets.CALISTA_DEPLOY_KEY }}
          port: ${{ secrets.CALISTA_SSH_PORT }}
          script: |
            whoami
            pwd
